name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print out hello-world
        run: echo "Hello, world."
      - name: Print out current directory
        run: pwd
      - name: Check out repository
        uses: actions/checkout@v3
      - name: list files and directory
        run: ls
